#!/bin/bash
sudo echo "y" | wee_database --add-column=co2_Temp --type=REAL
sudo echo "y" | wee_database --add-column=co2_Hum --type=REAL
sudo echo "y" | wee_database --add-column=co2_Batt --type=REAL
sudo echo "y" | wee_database --add-column=pm25_1 --type=REAL
sudo echo "y" | wee_database --add-column=pm25_2 --type=REAL
sudo echo "y" | wee_database --add-column=pm25_3 --type=REAL
sudo echo "y" | wee_database --add-column=pm25_4 --type=REAL
sudo echo "y" | wee_database --add-column=pm25_Batt1 --type=REAL
sudo echo "y" | wee_database --add-column=pm25_Batt2 --type=REAL
sudo echo "y" | wee_database --add-column=pm25_Batt3 --type=REAL
sudo echo "y" | wee_database --add-column=pm25_Batt4 --type=REAL
sudo echo "y" | wee_database --add-column=leafWet3 --type=REAL
sudo echo "y" | wee_database --add-column=leafWet4 --type=REAL
sudo echo "y" | wee_database --add-column=leafWet5 --type=REAL
sudo echo "y" | wee_database --add-column=leafWet6 --type=REAL
sudo echo "y" | wee_database --add-column=leafWet7 --type=REAL
sudo echo "y" | wee_database --add-column=leafWet8 --type=REAL
sudo echo "y" | wee_database --add-column=leafWetBatt1 --type=REAL
sudo echo "y" | wee_database --add-column=leafWetBatt2 --type=REAL
sudo echo "y" | wee_database --add-column=leafWetBatt3 --type=REAL
sudo echo "y" | wee_database --add-column=leafWetBatt4 --type=REAL
sudo echo "y" | wee_database --add-column=leafWetBatt5 --type=REAL
sudo echo "y" | wee_database --add-column=leafWetBatt6 --type=REAL
sudo echo "y" | wee_database --add-column=leafWetBatt7 --type=REAL
sudo echo "y" | wee_database --add-column=leafWetBatt8 --type=REAL
sudo echo "y" | wee_database --add-column=leak_1 --type=REAL
sudo echo "y" | wee_database --add-column=leak_2 --type=REAL
sudo echo "y" | wee_database --add-column=leak_3 --type=REAL
sudo echo "y" | wee_database --add-column=leak_4 --type=REAL
sudo echo "y" | wee_database --add-column=leak_Batt1 --type=REAL
sudo echo "y" | wee_database --add-column=leak_Batt2 --type=REAL
sudo echo "y" | wee_database --add-column=leak_Batt3 --type=REAL
sudo echo "y" | wee_database --add-column=leak_Batt4 --type=REAL
sudo echo "y" | wee_database --add-column=lightning_Batt --type=REAL
sudo echo "y" | wee_database --add-column=soilMoist5 --type=REAL
sudo echo "y" | wee_database --add-column=soilMoist6 --type=REAL
sudo echo "y" | wee_database --add-column=soilMoist7 --type=REAL
sudo echo "y" | wee_database --add-column=soilMoist8 --type=REAL
sudo echo "y" | wee_database --add-column=soilMoistBatt1 --type=REAL
sudo echo "y" | wee_database --add-column=soilMoistBatt2 --type=REAL
sudo echo "y" | wee_database --add-column=soilMoistBatt3 --type=REAL
sudo echo "y" | wee_database --add-column=soilMoistBatt4 --type=REAL
sudo echo "y" | wee_database --add-column=soilMoistBatt5 --type=REAL
sudo echo "y" | wee_database --add-column=soilMoistBatt6 --type=REAL
sudo echo "y" | wee_database --add-column=soilMoistBatt7 --type=REAL
sudo echo "y" | wee_database --add-column=soilMoistBatt8 --type=REAL
sudo echo "y" | wee_database --add-column=soilTemp5 --type=REAL
sudo echo "y" | wee_database --add-column=soilTemp6 --type=REAL
sudo echo "y" | wee_database --add-column=soilTemp7 --type=REAL
sudo echo "y" | wee_database --add-column=soilTemp8 --type=REAL
sudo echo "y" | wee_database --add-column=soilTempBatt1 --type=REAL
sudo echo "y" | wee_database --add-column=soilTempBatt2 --type=REAL
sudo echo "y" | wee_database --add-column=soilTempBatt3 --type=REAL
sudo echo "y" | wee_database --add-column=soilTempBatt4 --type=REAL
sudo echo "y" | wee_database --add-column=soilTempBatt5 --type=REAL
sudo echo "y" | wee_database --add-column=soilTempBatt6 --type=REAL
sudo echo "y" | wee_database --add-column=soilTempBatt7 --type=REAL
sudo echo "y" | wee_database --add-column=soilTempBatt8 --type=REAL
sudo echo "y" | wee_database --add-column=sunshine_hours --type=REAL
sudo echo "y" | wee_database --add-column=sunshine_time --type=REAL
sudo echo "y" | wee_database --add-column=ws90cap_volt --type=REAL
sudo echo "y" | wee_database --add-column=sunshineDur --type=REAL
sudo echo "y" | wee_database --add-column=rainDur --type=REAL
sudo echo "y" | wee_database --add-column=hailDur --type=REAL

