#!/bin/bash
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=appTemp --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=appTemp1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=batteryStatus8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=cloudbase --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=co --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=co2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=dewpoint1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=forecast --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=hailBatteryStatus --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=heatindex1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=humidex --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=humidex1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=inDewpoint --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=inTempBatteryStatus --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=inTempBatteryStatusREAL --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=lightning_distance --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=lightning_disturber_count --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=lightning_energy --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=lightning_noise_count --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=lightning_strike_count --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=luminosity --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=maxSolarRad --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=nh3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=no2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=noise --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=o3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pb --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm10_0 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm1_0 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm2_5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=signal8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=snow --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=snowBatteryStatus --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=snowDepth --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=snowMoisture --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=snowRate --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=so2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=uvBatteryStatus --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=windrun --type=REAL

sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=co2_Temp --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=co2_Hum --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=co2_Batt --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm25_1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm25_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm25_3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm25_4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm25_Batt1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm25_Batt2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm25_Batt3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=pm25_Batt4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWet3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWet4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWet5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWet6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWet7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWet8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWetBatt1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWetBatt2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWetBatt3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWetBatt4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWetBatt5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWetBatt6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWetBatt7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leafWetBatt8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leak_1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leak_2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leak_3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leak_4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leak_Batt1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leak_Batt2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leak_Batt3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=leak_Batt4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=lightning_Batt --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoist5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoist6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoist7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoist8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoistBatt1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoistBatt2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoistBatt3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoistBatt4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoistBatt5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoistBatt6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoistBatt7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilMoistBatt8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTemp5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTemp6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTemp7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTemp8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTempBatt1 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTempBatt2 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTempBatt3 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTempBatt4 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTempBatt5 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTempBatt6 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTempBatt7 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=soilTempBatt8 --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=sunshine_hours --type=REAL
sudo echo "y" | wee_database --config=/etc/weewx/weewx.conf --add-column=sunshine_time --type=REAL

